### ISSUE TITLE
@BF2Statistics

### ISSUE THREAD

**Issue by bf2spy** [BF2Statistics/ClientLauncher#1]
the codes in Forms/Launcher.cs
```
            // Do we have any mods?
            if (i == 0) // it should be  if (i == 1) or it will not run.
            {
                MessageBox.Show(
                    "No mods detected in the bf2 mods folder. Unable to continue.", 
                    "Launch Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
                this.Load += new EventHandler(MyForm_CloseOnStart);
                return;
            }
```

**Comment by wilson212** [comment]
If "i" was to equal 1, that would mean there was a single found mod with the correctly formatted "mod.desc " file, which would mean a valid mod was found. I looked over that method in question "GetBF2ModsList()" and it is working as intended.

**Comment by bf2spy** [comment]
@wilson212   
happy new year!
I tested several times and find that the 64-bit system did not work  but on 32-bit systems it works.
So I comment it out
You should be right, Thank you very much for your reply!
